objects/JIRA_Issue_Key__c.object
<CustomObject>
    <fields>
        <fullName>Key_Name__c</fullName>
        <externalId>true</externalId>
        <label>Key Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>102400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Url__c</fullName>
        <label>Request Url</label>
        <type>TextArea</type>
    </fields>
    <label>JIRA Issue Key</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>JIRA Issue Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JIRA Issue Keys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JiraWebhookHandler.cls
@RestResource(urlMapping='/jiraapi/*')
global without sharing class JiraWebhookHandler {
    global class DefaultApiResponse{
        public String apiName;
        public Integer status;
    }

    @HttpPost
    global static DefaultApiResponse processJiraApiRequest(){
        RestRequest rrequest = RestContext.request;
        String keyId = rrequest.requestURI.substring(rrequest.requestURI.lastIndexOf('/')+1);     
        
        DefaultApiResponse response = new DefaultApiResponse();
        response.apiName = keyId;
        response.status = 200;
        
        JIRA_Issue_Key__c jir = new JIRA_Issue_Key__c();
        jir.Key_Name__c = keyId;
        jir.Request_Url__c = rrequest.requestURI;
        jir.Request_Body__c = rrequest.requestBody.toString();

        insert jir;
        /*if(Schema.SObjectType.JIRA_Issue_Key__c.isCreateable()){
            insert jir;
        }*/

        return response;
    }
}